import Foundation

/// Generated by build_dict.py (accent_dict.tsv). Keys are accent-free lowercase words.
public struct AccentDictionary {
    /// ecole -> école: accented without asking
    public var auto: [String: String] = [:]
    /// grace -> grâce: also English words, so accented only while the text is French
    public var autoFrench: [String: String] = [:]
    /// cote -> [côté, côte, coté, cote]: what right ⌥ cycles through, most frequent first
    public var cycle: [String: [String]] = [:]
    /// decide, a, ou...: the runner-up spelling is common enough to offer the choice list
    public var ambiguous: Set<String> = []
    /// aime -> aimé: the past participle, used after an auxiliary ("être aimé")
    public var participles: [String: String] = [:]

    public init() {}

    public init(contentsOf url: URL) throws {
        let text = try String(contentsOf: url, encoding: .utf8)
        for line in text.split(whereSeparator: \.isNewline) {
            let fields = line.split(separator: "\t").map(String.init)
            guard fields.count >= 3 else { continue }
            switch fields[0] {
            case "A": auto[fields[1]] = fields[2]
            case "F": autoFrench[fields[1]] = fields[2]
            case "C": cycle[fields[1]] = Array(fields.dropFirst(2))
            case "P": ambiguous.insert(fields[1])
            case "E": participles[fields[1]] = fields[2]
            default: break
            }
        }
    }
}
